# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: markjuruo's note
subtitle: 学习笔记
description: markjuruo's note——静下心来，记录知识
keywords: OI,信奥,学习笔记
author: markjuruo
language: zh-CN
timezone:



# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://markjuruo.ooo
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: yilia

symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git
    repo: https://markjuruo:lzh666lzh666@github.com/markjuruo/markjuruo.github.io.git
  - type: git
    repo: https://markjuruo:linzhihan@git.coding.net/markjuruo/markjuruo.coding.me.git
  #- type: git
  #  repo: https://markjuruo:lzh581b@gitee.com/markjuruo/markjuruo.gitee.io.git
  - type: git
    repo: https://markjuruo:linzhihan@git.coding.net/markjuruo/markjuruo.coding.me.git
    branch: src
    extend_dirs: /
    ignore_hidden: false
    ignore_pattern:
        public: .

# Extensions
## Plugins: http://hexo.io/plugins/
#RSS订阅
plugin:
- hexo-generator-feed
#Feed Atom
feed:
type: atom
path: atom.xml
limit: 20

permalink_pinyin:
  enable: true    # Enable this plugin
  separator: '-'  # Separator of the slug, default: '-'

# hexo-admin authentification
admin:
  username: linzhihan
  password_hash: $2a$10$4nqMXDfB4CKKYQydRXDiBOWog34naa3mw9oz3xDXvSO.rIRqnzl1a
  secret: 581b

jsonContent:
    meta: false
    pages: false
    posts:
      title: true
      date: true
      path: true
      text: false
      raw: false
      content: false
      slug: false
      updated: false
      comments: false
      link: false
      permalink: false
      excerpt: false
      categories: false
      tags: true
